### ISSUE TITLE
Wrong return type for std::isinf/isnan(double)

### ISSUE THREAD

**Issue by ZzEeKkAa** [conda-forge/ctng-compiler-activation-feedstock#106]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Really don't want to duplicate issues, but hope to get the response here faster, since this issue is reproducable both with pkgs::main and conda-forge. It also reproducible for both clang++ and g++. Tested with latest gcc version (13), but environment from pkgs::main:

https://github.com/ContinuumIO/anaconda-issues/issues/13367

### Installed packages

```shell
# packages in environment at /home/yevhenii/.miniconda3/envs/compiler:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
_sysroot_linux-64_curr_repodata_hack 3                   haa98f57_10    defaults
binutils_impl_linux-64    2.38                 h2a08ee3_1    defaults
binutils_linux-64         2.38.0               hc2dff05_0    defaults
gcc_impl_linux-64         11.2.0               h1234567_1    defaults
gcc_linux-64              11.2.0               h5c386dc_0    defaults
gxx_impl_linux-64         11.2.0               h1234567_1    defaults
gxx_linux-64              11.2.0               hc2dff05_0    defaults
kernel-headers_linux-64   3.10.0              h57e8cba_10    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libgcc-devel_linux-64     11.2.0               h1234567_1    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-devel_linux-64  11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
sysroot_linux-64          2.17                h57e8cba_10    defaults
```

### Environment info

```shell
active environment : compiler
    active env location : /home/yevhenii/.miniconda3/envs/compiler
            shell level : 1
       user config file : /home/yevhenii/.condarc
 populated config files : /home/yevhenii/.condarc
          conda version : 24.3.0
    conda-build version : 24.3.0
         python version : 3.10.12.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.3.0=0
                          __glibc=2.35=0
                          __linux=5.15.123.1=0
                          __unix=0=0
       base environment : /home/yevhenii/.miniconda3  (writable)
      conda av data dir : /home/yevhenii/.miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/yevhenii/.miniconda3/pkgs
                          /home/yevhenii/.conda/pkgs
       envs directories : /home/yevhenii/.miniconda3/envs
                          /home/yevhenii/.conda/envs
               platform : linux-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.12 Linux/5.15.123.1-microsoft-standard-WSL2 ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : /home/yevhenii/.netrc
           offline mode : False
```

**Comment by h-vetinari** [comment]
This is not really a duplication - you should raise an issue for the `defaults` packages with anaconda, and or the conda-forge packages here - that's all fine. That said, each issue should be stand-alone (while of course it can/should refer to related issues) - so please complete the information here, and provide the environment information for the conda-forge packages used.

**Comment by isuruf** [comment]
This is not anaconda package support. Please reopen if you can reproduce with conda-forge packages.

**Comment by h-vetinari** [comment]
> Please reopen if you can reproduce with conda-forge packages.

OP said it's reproducible with conda-forge packages. But as I asked, the information in the issue needs to be complete, then I'll happily reopen.

**Comment by ZzEeKkAa** [comment]
@h-vetinari @isuruf thank you for the quick reply. I've opened the issue with `conda-forge` information:
https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/108

**Comment by ZzEeKkAa** [comment]
@h-vetinari what is the right place to open issues for the anaconda compilers? So far, I guess `https://github.com/ContinuumIO/anaconda-issues` is the best place, could you confirm it?

**Comment by h-vetinari** [comment]
> @h-vetinari what is the right place to open issues for the anaconda compilers? So far, I guess `https://github.com/ContinuumIO/anaconda-issues` is the best place, could you confirm it?

Best to ask on the conda [discourse](https://conda.discourse.group/) I think. There's also some separate feedstocks ([example](https://github.com/AnacondaRecipes/ctng-compiler-activation-feedstock)) under AnacondaRecipes, but I'm not sure if someone checks the issue tracker there. As Isuru said, we're not supporting anaconda packages, only conda-forge ones.
