### ISSUE TITLE
linux-aarch64 gcc missing libquadmath.so

### ISSUE THREAD

**Issue by yejianbang** [conda-forge/ctng-compiler-activation-feedstock#107]
### Comment:

My architecture is linux-arch64, and I installed gcc using anaconda. However, I found that the libquadmath library was missing after installation. I hope relevant personnel can fix it

**Comment by yejianbang** [comment]
![image](https://github.com/conda-forge/ctng-compiler-activation-feedstock/assets/145335562/726c64ff-2644-4bfe-82aa-712f8c32acc1)
This is a bad soft link

**Comment by h-vetinari** [comment]
Please provide all relevant information demanded by the issue template, especially the output of `conda list` and `conda info`.

**Comment by isuruf** [comment]
Please re-open with the requested info.
