### ISSUE TITLE
C++17 flag and conda-build

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/ctng-compiler-activation-feedstock#20]
In [conda_build_config.yaml](https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/master/recipe/conda_build_config.yaml#L29-L33), the C++ standard flag is forcibly set to C++17. However, the default behavior of GCC7 is to set that flag to C++14.

This is **not something that can be reverted** because new packages built with C++14 would then be have ODR violations with their C++17-compiled dependencies (while the oposite would not cause any issue).

However, this is an issue when using these compilers in CI with conda-built dependencies, because we then always need to specify `--std=c++17`.

It would be nice to change this package so that the default behavior of conda's GCC 7 is to use C++17, and not just in the case of conda-build.

But at a higher level, I *think* that we should try to be as close as possible to the off-the-shelf behavior of packages (default configuration, as few patches as possible) to not have that kind of side effects.

**Comment by SylvainCorlay** [comment]
cc @mingwandroid - I recall we discussed the defaulting to c++17 in conda-build at some point.

**Comment by isuruf** [comment]
We've decided not to bump the C++ version in macOS (It's currently C++14), but we can't undo it here.
