### ISSUE TITLE
Why isn't `CMAKE_BUILD_TYPE=Release` included in `CMAKE_ARGS`?

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/ctng-compiler-activation-feedstock#94]
### Comment:

I recently started using the auto-defined `CMAKE_ARGS` environment variable for my CMake-based conda builds, as suggested in the [conda-forge docs on using CMake](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-cmake). Not only is it convenient, but I agree with the perspective in https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/77#issuecomment-1145159371 that using shared CMake settings helps keep the conda-forge ecosystem consistent.

However, I was recently surprised to learn that `CMAKE_BUILD_TYPE=Release` is not set by `activate-gcc.sh` in this repo (https://github.com/conda-forge/staged-recipes/pull/23297). It is set by [`activate-clang.sh`](https://github.com/conda-forge/clang-compiler-activation-feedstock/tree/baa929fbf270cba69c2b9a435f030df2bd1a2035) for osx builds and by [`activate.bat`](https://github.com/conda-forge/vc-feedstock/blob/97ada02cef22b60a8d64c71c16f58297046bf24a/recipe/activate.bat#L83) for MSVC builds on Windows. I wasn't able to find any discussion on the motivation for this inconsistency across the platforms. In fact, all I could find was a discussion that was debating setting `CMAKE_BUILD_TYPE=None` (#87, https://github.com/conda-forge/conda-forge.github.io/issues/1859).

Is there a particular motivation why `CMAKE_BUILD_TYPE=Release` is the default for osx and win builds, but not linux? If not, can I send I PR to include `CMAKE_BUILD_TYPE=Release` in `CMAKE_ARGS`?

**Comment by isuruf** [comment]
> If not, can I send I PR to include CMAKE_BUILD_TYPE=Release in CMAKE_ARGS?

Yes, please

**Comment by isuruf** [comment]
Instead of
```
cmake ${CMAKE_ARGS} .
```
you do
```
cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Debug .
```

**Comment by jakirkham** [comment]
It's ok to specify `CMAKE_BUILD_TYPE` twice?

cc @robertmaynard

**Comment by pitrou** [comment]
Why has this been done? It has started [breaking CI builds](https://github.com/apache/arrow/actions/runs/5904814214/job/16017685263?pr=37174) for us in Arrow. The build type is per-environment setting, not something that Conda should dictate to users. For example, it is recommended to build in Debug mode for development.

**Comment by pitrou** [comment]
> Not only is it convenient, but I agree with the perspective in [#77 (comment)](https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/77#issuecomment-1145159371) that using shared CMake settings helps keep the conda-forge ecosystem consistent.

I think this conflates two different things:
* using conda environments for general development
* using conda environments in order to build conda packages for conda-forge

There really should be two different environment variables for those. For example `CMAKE_ARGS` and `CMAKE_ARGS_FOR_CONDA_BUILD`.

**Comment by xhochy** [comment]
We could set some variables like`BUILD_TYPE` conditionally on the activation being run inside of `CONDA_BUILD`. We already have a conditional block for this in https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/688de6d31129e584a5f164a28c50806353056c63/recipe/activate-gcc.sh#L86

**Comment by jdblischak** [comment]
> It has started breaking CI builds for us in Arrow.

@pitrou I'm sorry this has caused an issue for you. I appreciate that unexpected build failures are always frustrating.

> Why has this been done?

The motivation is two-fold:

* To be consistent with the other conda-forge compilers: [vc-feedstock](https://github.com/conda-forge/vc-feedstock/blob/97ada02cef22b60a8d64c71c16f58297046bf24a/recipe/activate.bat#L83) and [clang-compiler-activation-feedstock](https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/baa929fbf270cba69c2b9a435f030df2bd1a2035/recipe/activate-clang.sh#L139). These both set `CMAKE_BUILD_TYPE=Release` in the env var `CMAKE_ARGS`, so it is inconsistent for the linux builds to be the exception
* To promote [consistency in the builds](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-cmake) throughout the conda-forge ecosystem

> There really should be two different environment variables for those. For example `CMAKE_ARGS` and `CMAKE_ARGS_FOR_CONDA_BUILD`.

Could you please explain why the [workaround noted above](https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/94#issuecomment-1642841933) isn't ideal for your setup? If you know you need a specific build type, you can include it in the call to cmake, and the value set in this repository is overridden. For example, if your CI builds use `cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Debug .`, then they will be unaffected by what conda-forge decides to set as its default.

**Comment by pitrou** [comment]
> Could you please explain why the [workaround noted above](https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/94#issuecomment-1642841933) isn't ideal for your setup?

It certainly works. It's just that 1) it's more fragile (you have to make sure you use the correct parameter order in your `cmake` invocation) 2) the change broke things for us in a rather gratuitous way, and without warning.

Certainly, regardless of the final decision made by conda-forge, we can easily work around it... However, in general, I don't think conda/conda-forge should change compilation defaults except where necessary (such as setting the correct library search path).

A general request: please think about user experience instead of doing unexpected changes like that. Also, I would suggest looking at what other package repositories do, because it can serve as a reference for good packaging practices. If Ubuntu/Fedora/etc. don't force the default CMake build type, why would conda-forge behave differently?

**Comment by pitrou** [comment]
(in our particular case, "broke things for us in a rather gratuitous way" implies that we had 1) to research the underlying cause of our CI issues 2) try a workaround and schedule a general CI rebuild to ensure it doesn't break something else; that's easily one or two hours lost, not to mention the annoyance of unrelated CI failures on pending PRs)
