### ISSUE TITLE
Define    -DPython_FIND_VIRTUALENV=First in CMAKE_ARGS

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/ctng-compiler-activation-feedstock#99]
### Comment:

Would it make sense to define this?

it seemed that defining `Pythin_FIND_VIRTUALENV` helped in 

https://github.com/conda-forge/openimageio-feedstock/pull/87

https://cmake.org/cmake/help/latest/module/FindPython.html

cc: @h-vetinari

**Comment by isuruf** [comment]
You should set `Python3_FIND_STRATEGY=LOCATION`. This is done by many feedstocks and I think it's somewhere in our docs.

**Comment by isuruf** [comment]
And also patch upstream projects to use https://cmake.org/cmake/help/latest/policy/CMP0094.html#policy:CMP0094

**Comment by hmaarrfk** [comment]
thanks

**Comment by hmaarrfk** [comment]
Reading this section was helpful to me:
https://cmake.org/cmake/help/latest/manual/cmake-policies.7.html#introduction
